export const POSTS_AVAILABLE = 'POSTS_AVAILABLE';
export const VOTED_POST = 'VOTED_POST';
export const READ_POST = 'READ_POST';
export const DELETED_POST = 'DELETED_POST';
export const CATEGORIES_AVAILABLE = 'CATEGORIES_AVAILABLE';
export const SORT_POSTS = 'SORT_POSTS';
export const ADD_POST = 'ADD_POST';
export const UPDATE_POST = 'UPDATE_POST';

export const COMMENTS_AVAILABLE = 'COMMENTS_AVAILABLE';
export const ADD_COMMENT = 'ADD_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
